### ISSUE TITLE
Reset DB command does not work as intended on v2.1.0-beta.1

### ISSUE THREAD

**Issue by MericFeyz** [Open-IoT-Service-Platform/platform-launcher#501] opened 2021-09-30 10:52 UTC
If the command works as intended, then it should (at least) wipe all users in the database and recreate the system users again. Currently it does not delete any users.

Steps to reproduce:

1. add user to the database `kubectl -n oisp exec <FrontendPod> -- node /app/admin addUser <Username> <Password>`
2. reset the DB `kubectl -n oisp exec <FrontendPod> -- node /app/admin resetDB`
Expected: the user is not in the database anymore
Instead: the user is still in there

**Comment by oguzcankirmemis** [comment] 2021-10-01 12:20
This is not a bug, resetDB does not reset Keycloak database, only resets the frontend database. If you also want to wipe out the users in keycloak, use the admin tool resetKeycloakUsers. Remember to use the resetDB again thereafter, since resetDB also creates the necessary system users for the platform. You can reopen the issue, if I am missing something, closing it for now.

**Closed as completed by oguzcankirmemis** 2021-10-01 12:20 UTC
Labels: bug
